wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-05
architecture:
  desc: null
  value: ViT-B/32
dataset:
  desc: null
  value: Qulit-1M
epochs:
  desc: null
  value: 40
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707305206.792074
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.2
      8:
      - 5
      - 9
      13: linux-x86_64
